name: Deploy Quarto Site

  on:
    push:
      branches: [main]
      paths:
        - 'course_site/**'
        - '.github/workflows/**'
        - 'AGENTS.md'
        - 'DAY_1/**'
    workflow_dispatch:

  concurrency:
    group: 'pages'
    cancel-in-progress: false

  permissions:
    contents: write
    pages: write
    id-token: write

  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 'stable'

        - name: Install Python dependencies
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - run: pip install --upgrade pip
        - run: pip install jupyter nbconvert

        - name: Render Quarto site
          run: quarto render course_site

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: course_site/_site

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
